# Generated by Django 3.0 on 2020-04-10 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0002_auto_20200410_0922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='registration_date',
        ),
        migrations.AddField(
            model_name='vendor',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='vendor',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_eans',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
