# Generated by Django 2.2.5 on 2020-04-12 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
